---

- name: Regeln auf allen Webserver Maschinen durchsetzen
  hosts: webserver
  become: true
  roles:
    - apache


- name: Regeln auf allen Datenbank Maschinen durchsetzen
  hosts: webserver
  become: true
  roles:
    - postgresql
