---

- name: Install PostgreSQL packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - postgresql
    - postgresql-client
    - postgresql-contrib

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
